/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DataPreProcess.ConvertedTrace;
import DataPreProcess.DataConvert;
import DataPreProcess.Trace;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.List;
import javax.swing.JFileChooser;

/**
 *
 * @author Moliang
 */
public class Main_Frame extends javax.swing.JFrame {

    private List<Trace> traces;
    private List<ConvertedTrace> converted_traces;

    /**
     * Creates new form Main_Frame
     */
    public Main_Frame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser_Open = new javax.swing.JFileChooser();
        jButton_Convert = new javax.swing.JButton();
        jMenuBar = new javax.swing.JMenuBar();
        jMenu_File = new javax.swing.JMenu();
        jMenuItem_OpenFile = new javax.swing.JMenuItem();
        jMenu_Edit = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton_Convert.setText("Convert");
        jButton_Convert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ConvertActionPerformed(evt);
            }
        });

        jMenu_File.setText("File");

        jMenuItem_OpenFile.setText("Open file");
        jMenuItem_OpenFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_OpenFileActionPerformed(evt);
            }
        });
        jMenu_File.add(jMenuItem_OpenFile);

        jMenuBar.add(jMenu_File);

        jMenu_Edit.setText("Edit");
        jMenuBar.add(jMenu_Edit);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(139, 139, 139)
                .addComponent(jButton_Convert)
                .addContainerGap(190, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(137, Short.MAX_VALUE)
                .addComponent(jButton_Convert)
                .addGap(119, 119, 119))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem_OpenFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_OpenFileActionPerformed
        // TODO add your handling code here:
        int response = jFileChooser_Open.showOpenDialog(this);
        if (response == JFileChooser.APPROVE_OPTION) {
            // Read csv file here
            String address = jFileChooser_Open.getSelectedFile().getAbsolutePath();
            System.out.println(address);
            ReadFile file = new ReadFile();
            file.readCsvFile(address);
            traces = file.get_Traces();
        }
    }//GEN-LAST:event_jMenuItem_OpenFileActionPerformed

    private void jButton_ConvertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ConvertActionPerformed
        // TODO add your handling code here:
        System.out.println("Converting traces... ");
        converted_traces = DataConvert.Convert(traces);
        int response = jFileChooser_Open.showOpenDialog(this);
        if (response == JFileChooser.APPROVE_OPTION) {
            // Read csv train_file_name here
            String output_file = jFileChooser_Open.getSelectedFile().getAbsolutePath();
            if (!output_file.contains(".csv")) {
                output_file = output_file + ".csv";
            }
            System.out.println("Writing file: " + output_file);
            Export_file(output_file);
        }
    }//GEN-LAST:event_jButton_ConvertActionPerformed

    private void Export_file(String filename) {
        FileWriter myWriter = null;
        try {
            File myFile = new File(filename);
            myWriter = new FileWriter(myFile, false); // true to append,false to overwrite
            StringBuilder strBd = new StringBuilder();

            String title = "";

//            for (Vector<String> line : Result_table) {
//                for (int index = 0; index < line.size(); index++) {
//                    strBd.append(line.get(index));
//                    if (index != line.size() - 1) {
//                        strBd.append(',');
//                    }
//                }
//                strBd.append("\n");
//            }
            myWriter.write(strBd.toString());
            myWriter.close();

        } catch (IOException ex) {

        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main_Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Convert;
    private javax.swing.JFileChooser jFileChooser_Open;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenuItem jMenuItem_OpenFile;
    private javax.swing.JMenu jMenu_Edit;
    private javax.swing.JMenu jMenu_File;
    // End of variables declaration//GEN-END:variables
}
